url: "https://www.necromancers-gift.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Necromancer's Gift" # the name of your site, e.g. ACME Corp.
author: "ldd"

plugins:
  - jekyll-feed

sass:
  style: compressed
repository: necromancers-gift/necromancers-gift.github.io
# github: [metadata]
github_issues_repository: "necromancers-gift/necromancers-gift.github.io"

exclude: ["presskit_template", "scripts", ".env"]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: "en"
  - scope:
      path: "fr"
    values:
      lang: "en"
